// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoiICLXjj4ZCLfVyZdO65ZQzKtHuohzCw',
    appId: '1:36665228486:web:306da29b73a37f4df92bc7',
    messagingSenderId: '36665228486',
    projectId: 'flash-chatt-c344e',
    authDomain: 'flash-chatt-c344e.firebaseapp.com',
    storageBucket: 'flash-chatt-c344e.appspot.com',
    measurementId: 'G-ZGMH9XGENF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-0S6xQDUu_bUbEoMvfrK3UrmjsqDm68',
    appId: '1:36665228486:android:cf3f1c9b51ce5f5cf92bc7',
    messagingSenderId: '36665228486',
    projectId: 'flash-chatt-c344e',
    storageBucket: 'flash-chatt-c344e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoiICLXjj4ZCLfVyZdO65ZQzKtHuohzCw',
    appId: '1:36665228486:web:fed06565a4245cd6f92bc7',
    messagingSenderId: '36665228486',
    projectId: 'flash-chatt-c344e',
    authDomain: 'flash-chatt-c344e.firebaseapp.com',
    storageBucket: 'flash-chatt-c344e.appspot.com',
    measurementId: 'G-1B9EXMPWDM',
  );
}
